Labs/Models/Invoices.cs
namespace Labs.Models
{
    public class Invoices
    {
        public Invoices()
        {
            InvoiceItems = new List<InvoiceDetail>();
        }

        public int InvoiceId { get; set; } 
        public int InvoiceNumber { get; set; }  

        public DateTime DateTime { get; set; }

        public string Discription { get; set;  }

        public int CustomerId { get; set; }

        public string HasShipped { get; set; }          

        public List<InvoiceDetail> InvoiceItems { get; set; }   
        

    }
}

Labs/Areas/admin/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using Labs.Models;
using Microsoft.VisualBasic;

namespace Labs.Areas.admin.Controllers
{
    [Area("admin")]
    public class InvoicesController : Controller
    {
        public IActionResult Index()
        {
            List<Customers> lstCustomers = new List<Customers>();

            lstCustomers.Add(new Customers()
            {
                CustomerId = 1,
                CustomerName = "Ahmed"
            });

            lstCustomers.Add(new Customers()
            {
                CustomerId = 2,
                CustomerName = "Mohamed"
            });


            lstCustomers.Add(new Customers()
            {
                CustomerId = 3 , 
                CustomerName = "Hafez"
            });
             ViewBag.Customers = lstCustomers;

            var invoice = new Labs.Models.Invoices();
            invoice.InvoiceItems.Add(new InvoiceDetail()
            {
                 price =50 , 
                 Quantity = 1 ,
                 ItemId= 1  , 



            });
            invoice.InvoiceItems.Add(new InvoiceDetail()
            {
                price = 80,
                Quantity = 4,
                ItemId = 2,



            });

            invoice.InvoiceItems.Add(new InvoiceDetail()
            {
                price = 100,
                Quantity = 5 , 
                ItemId = 3,



            });
            return View(invoice);
        }
    }
}

Labs/Areas/admin/Views/Invoices/Index.cshtml
@model Invoices  
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title"> Form elements </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Forms</a></li>
                <li class="breadcrumb-item active" aria-current="page">Form elements</li>
            </ol>
        </nav>
    </div>
    <form class="forms-sample" method="post" enctype="multipart/form-data"
          asp-controller="Invoices" asp-action="Index" role="form" multiple>
        <div class="row">

            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <h4 class="card-title">Default form</h4>
                        <p class="card-description"> Basic form layout </p>
                        


                        <div class="form-group">
                            <label for="exampleInputUsername1">Invoice Number</label>
                            <input asp-for="InvoiceNumber" type="number" class="form-control" placeholder="Invoice Numer">
                            <span class="text-danger" asp-validation-for="InvoiceNumber"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">Invoice Date</label>
                            <input asp-for="DateTime" type="date" class="form-control" placeholder="Invoice Date">
                            <span class="text-danger" asp-validation-for="DateTime"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">Description</label>
                            <input asp-for="Discription" type="text" class="form-control" placeholder="Desciption">
                            <span class="text-danger" asp-validation-for="Discription"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">Customers</label>
                            <select asp-for="CustomerId"
                                  asp-items="@(new SelectList(ViewBag.Customers,"CustomerId","CustomerName"))">
                              </select>
                            <span class="text-danger" asp-validation-for="Discription"></span>
                        </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputUsername1">Shaped</label>
                            <input asp-for="HasShipped" type="checkbox" checked="@Model.HasShipped" >
                            <span class="text-danger" asp-validation-for="HasShipped"></span>
                            <br />
                            <br />
                        <table id="DataTable" class="table table-hover">
                               <thead>
                                   <tr>
                                        <th>Quantity</th>


                                       <th>Price</th>
                                       

                                       <th>Delete</th>

                                   </tr>
                               </thead>
                               <tbody>
                                    @for(int i = 0 ; i<Model.InvoiceItems.Count;i++)
                                    {
                                        <tr>
                                       <td>
                                                <input asp-for="@Model.InvoiceItems[i].Quantity" />
                                                <span asp-validation-for="@Model.InvoiceItems[i].price"></span>

                                       </td>
                                       <td>
                                                <input asp-for="@Model.InvoiceItems[i].Quantity" />
                                                <span asp-validation-for="@Model.InvoiceItems[i].Quantity"></span>
                                               
                                       </td>
                                            <td>
                                                <input value="Delete" type="button" class="btn btn-danger"/>

                                            </td>
                                        <td>
                                            <input />


                                        </td>
                                   </tr>
                                    }
                               </tbody>
                            </table>
                            

                            <input type="button" value="Add New Item" class="btn btn-info"
                               onclick="AddRow()" />


                        <button type="submit" formmethod="post" class="btn btn-gradient-primary me-2">@ResGeneral.lblSave</button>
                    </div>
                </div>
            </div>
            


        </div>
    </form>

</div>
    
@section Scripts
   {

   
              
            <script>
                 function AddRow()
                 {
            var table = document.getElementById("DataTable");
            var rows = table.getElementByTagName("tr") ;
            var rowHtml = rows[rows.length - 1].outerHTML;
                     

                     var newRow = table.insertRow() ; 
                     newRow.outerHTML = rowHtml ; 

                 }
            </script>
   }